// GÉNÉRÉ depuis les templates du Drive (assets/Drive/*.docx) — ne pas éditer à la main.
// Chaque niveau : liste de domaines, chaque domaine une liste de libellés de compétences.

export interface TemplateDomaine { nom: string; competences: string[]; }

export const MATERNELLE_DOMAINES: Record<string, TemplateDomaine[]> = {
  PS: [
  { nom: 'APPRENDRE ET VIVRE ENSEMBLE', competences: [
      'Je respecte les règles de politesse simple (dire bonjour, s’il te plaît, merci, au revoir…...) spontanément ou sur sollicitation de l’adulte.',
      'Je nomme mes camarades',
      'J’identifie les adultes de l’école et leur fonction',
      'Je respecte les autres',
      'Je respecte les règles de la classe',
      'J’écoute attentivement quand on me parle',
      'J’exécute une tâche simple en autonomie',
      'Je mène mon travail à bien',
      'Je m’intègre à la vie de groupe',
      'Je m’habille seul',
      'Je contrôle mes émotions',
  ] },
  { nom: 'A- L’ORAL', competences: [
      'J’entre en relation avec les autres par la médiation de la parole',
      'Je prends la parole lors des moments collectifs',
      'Je chante une comptine devant les autres',
      'Je comprends une consigne simple',
      'Je comprends et reformule une histoire simple',
      'J’écoute en silence une histoire ou un poème',
      'Je dis ce que j’ai appris',
      'J’utilise le JE pour expliquer ce que je fais',
      'Je produis des phrases simples',
  ] },
  { nom: 'B- L’ECRIT', competences: [
      'Je reconnais mon nom écrit en lettre capitales',
      'Je réalise des graphismes simples : points, traits, ronds',
      'Je tiens correctement l’instrument',
      'Je distingue les lettres des autres formes graphiques',
      'Je distingue le livre des autres supports',
  ] },
  { nom: '2- Agir, s’exprimer, comprendre à travers l’activité physique', competences: [
      'Je participe avec confiance à des activités libres ou guidées',
      'Je participe à des jeux collectifs en respectant les règles et mes camarades',
      'Je coordonne mes mouvements pour courir, sauter, lancer, recevoir…',
      'Je me déplace de différentes façons (ramper, rouler, …)',
      'Je participe à une ronde ou à un jeu dansé',
      'Je coopère ou j’interagis en respectant les rôles de chacun',
  ] },
  { nom: '3-Agir, s’exprimer, comprendre à travers les activités artistiques', competences: [
      'Je dessine et je peins avec plaisir',
      'Je nomme les principales couleurs',
      'J’utilise les techniques apprises en classe',
      'Je tiens mes ciseaux correctement',
      'J’utilise la colle à bon escient',
      'Je mémorise les comptines apprises en classe et je sais les dire ou les chanter',
      'Je chante avec les autres',
  ] },
  { nom: '4. Construire les premiers outils pour structurer sa pensée', competences: [
      'Je connais la comptine jusqu’à 10',
      'Je dénombre des quantités jusqu’à 5',
      'Je réalise des collections de 5 éléments',
      'Je reconnais et je sais écrire les chiffres jusqu’à 5',
      'Je compare deux quantités',
      'Je trie des objets selon leur forme, leur taille',
      'Je distingue les lignes ouvertes et les lignes fermées',
      'Je réalise un puzzle simple',
      'Je continue un algorithme',
  ] },
  { nom: '5. Explorer le monde', competences: [
      'Je connais les différents lieux de l’école',
      'Je connais les principaux principes spatiaux',
      'Je peux suivre un parcours décrit oralement',
      'Je me repère dans la journée',
      'Je me repère sur un calendrier simplifié (hier, aujourd’hui, demain)',
      'Je mets dans l’ordre 3, 4 images séquentielles',
      'Je nomme quelques parties de mon corps',
      'Je me lave les mains',
      'Je connais les gestes pour respecter l’environnement',
      'Je connais les cinq sens',
  ] }
  ],
  MS: [
  { nom: 'APPRENDRE ENSEMBLE ET VIVRE ENSEMBLE', competences: [
      'Comprendre la fonction de l’école',
      'Je respecte les règles de politesse (bonjour, au revoir, s’il te plait, merci)',
      'Je nomme mes camarades',
      'J’identifie les adultes de l’école et leur fonction',
      'Je respecte les autres',
      'Je respecte les règles de la classe',
      'J’écoute attentivement quand on me parle',
      'J’exécute une tâche simple en autonomie',
      'Je mène mon travail à bien',
  ] },
  { nom: 'L’ORAL', competences: [
      'Je m’exprime avec un langage structuré',
      'Je participe à un échange collectif en écoutant autrui et en attendant mon tour de parole',
      'Je relate un événement inconnu des autres',
      'Je dis ou chante une dizaine de comptines',
      'Je comprends une consigne',
      'Je comprends et reformule une histoire',
      'J’écoute en silence une histoire ou un poème',
      'J’ai acquis et je sais utiliser un vocabulaire pertinent',
      'J’ai acquis la conscience des sons',
      'Je distingue des mots dans un énoncé oral simple',
  ] },
  { nom: 'L’ECRIT', competences: [
      'Je reconnais et écris mon nom en lettres capitales',
      'Je reconnais la plupart des lettres de l’alphabet',
      'Je tiens correctement l’instrument scripteur',
      'Je reconnais les supports d’écrits utilisés en classe',
      'Je réalise les bases de l’écriture : cercles, traits verticaux, traits horizontaux, boucles, ondulations.',
  ] },
  { nom: '2- Agir, s’exprimer, comprendre à travers l’activité physique', competences: [
      'Je coordonne mes mouvements pour marcher, sauter, courir, lancer, recevoir, tirer',
      'Je joue à des jeux collectifs en respectant les règles et mes camarades',
      'Je participe avec confiance à des jeux libres ou guidés',
      'Je participe à une ronde ou à un jeu dansé',
      'Je m’exprime sur un rythme musical',
      'Je me repère et sais me déplacer dans l’espace',
  ] },
  { nom: '3-Agir, s’exprimer, comprendre à travers les activités artistiques', competences: [
      'Je dessine et je sais dire ce que j’ai dessiné',
      'Je mémorise et chante une dizaine de comptines',
      'J’écoute des extraits sonores ou des musiques variées',
      'Je tiens mes ciseaux correctement',
      'J’applique des techniques simples : coller, assembler…',
      'Je réalise des constructions (lego, puzzle, …)',
  ] },
  { nom: '4. Construire les premiers outils pour structurer sa pensée', competences: [
      'Je connais la comptine numérique jusqu’à 20',
      'Je dénombre les quantités jusqu’à 10',
      'Je réalise des collections de 10 éléments',
      'Je trie des objets selon leur forme, leur taille et leur couleur',
      'Je décrie des formes simples : cercle, carré, triangle, rectangle',
      'Je reconstitue des puzzles de trente pièces',
      'Je réalise un collier en alternant les couleurs (algorithmes 1-4)',
  ] },
  { nom: '5. Explorer le monde', competences: [
      'Je me repère dans la journée',
      'J’utilise et comprends les concepts suivants : avant, après, hier, aujourd’hui, demain',
      'Je situe des événements les uns par rapport aux autres',
      'Je suis familiarisé avec le calendrier et l’horloge',
      'Je nomme les parties de mon corps',
      'Je comprends et applique les règles d’hygiène du corps, des locaux et de l’alimentation',
      'Je connais les cinq sens : les organes et leurs fonctions',
      'Je reconnais une situation de danger et j’alerte l’adulte',
      'Je respecte l’environnement (mettre les déchets à la poubelle, recycler, etc.)',
  ] }
  ],
  GS: [
  { nom: 'APPRENDRE ENSEMBLE ET VIVRE ENSEMBLE', competences: [
      'Je respecte les règles de politesse (bonjour, au revoir, s’il te plait, au revoir',
      'Je nomme mes camarades',
      'J’identifie les adultes de l’école et leur fonction',
      'Je respecte les autres',
      'Je respecte les règles de la classe',
      'Je mène mon travail à son terme',
      'Je m’intègre à la vie de groupe',
  ] },
  { nom: 'A- L’ORAL', competences: [
      'Je dis, décris et explique une activité après l’avoir terminée',
      'Je produis un discours oral compréhensible',
      'Je dis et chante des poèmes et des chansons apprises en classe',
      'Je comprends les consignes',
      'Je me repère dans un livre',
      'Je produis des phrases complexes',
      'J’acquiers un vocabulaire pertinent',
      'Je dénombre les syllabes d’un mot et je localise un son dans un mot',
      'Je discrimine des sons proches',
      'Je mets en relation des sons et des lettres',
  ] },
  { nom: 'B- L’ECRIT', competences: [
      'Je reconnais la plupart des lettres de l’alphabet',
      'Je reconnais les différents types d’écrits',
      'Je reconnais la plupart des lettres de l’alphabet dans les trois écritures',
      'Je reconnais les différents types d’écrits',
      'Je reconnais la plupart des lettres de l’alphabet dans les trois écritures',
      'Je reproduis les graphismes qui amènent à l’acquisition de l’écriture cursive',
      'J’écris des mots simples en cursive',
  ] },
  { nom: '2- Agir, s’exprimer, comprendre à travers l’activité physique', competences: [
      'Je coordonne mes mouvements pour réaliser une performance',
      'Je participe à des jeux collectifs en respectant les règles et mes camarades',
      'Je participe sans contrainte à des jeux dansés',
      'Je me déplace avec aisance dans les parcours de motricité',
      'Je coordonne les gestes avec les autres lors des activités musicales',
  ] },
  { nom: '3-Agir, s’exprimer, comprendre à travers les activités artistiques', competences: [
      'Je dessine et je peins avec plaisir',
      'J’applique des techniques simples coller, assembler …',
      'Je réalise une production en volume',
      'Je mémorise et reproduis plusieurs chansons apprises en classe',
      'J’écoute un rythme musical',
      'Je reproduis un rythme musical simple',
  ] },
  { nom: '4. Construire les premiers outils pour structurer sa pensée', competences: [
      'Je connais la comptine numérique jusqu’à 30',
      'Je dénombre et crée une collection de 15 à 30 objets',
      'Je reconnais et sais écrire les chiffres jusqu’à 20',
      'Je dessine les formes simples : rond, carré, triangle, rectangle,',
      'Je découvre la notion de symétrie',
      'Je manipule les dés et les dominos',
      'Je résous des problèmes en passant par la manipulation',
      'Je compare des nombres en utilisant le vocabulaire : plus que, moins que, pareil, autant que.',
      'Je poursuis un algorithme',
      'Je compare des masses, réalise un équilibre avec une balance',
  ] },
  { nom: '5. Explorer le monde', competences: [
      'J’utilise le nom des jours et des mois',
      'Je situe des événements dans le temps',
      'Je me repère sur un calendrier mensuel',
      'Je repère des objets par rapport à moi',
      'Je connais ma droite et ma gauche',
      'Je nomme les différentes parties du corps',
      'Je connais les étapes de développement d’un animal et d’un végétal',
      'Je connais les cinq organes et les cinq sens correspondants',
      'Je reconnais une situation de danger et j’alerte l’adulte',
      'Je connais quelques règles d’hygiène',
      'Je respecte l’environnement (mettre les déchets à la poubelle, recycler,…',
      'Je désigne les matières : bois, métal, acier, …',
      'Je découvre les états de transformation de l’eau',
      'Je prends conscience de l’existence de l’air',
  ] }
  ],
};

export const ELEM_COMPETENCES: Record<string, TemplateDomaine[]> = {
  CP: [
  { nom: 'LANGAGE ORAL', competences: [
      'Écouter pour comprendre des messages oraux ou des textes lus par un adulte',
      'Raconter et décrire seul un récit étudié en classe (Dire pour être entendu et compris)',
      'Participer à des échanges dans des situations diversifiées',
      'Échanger avec ses camarades, donner son avis (Adopter une distance critique par rapport au langage produit',
  ] },
  { nom: 'LECTURE ET COMPREHENSION DE L’ÉCRIT', competences: [
      'Identifier des mots, les mots-outils, les phrases de manière de plus en plus aisée (inconnus réguliers ou irréguliers mémorisés)',
      'Connaitre le nom des lettres et l’ordre alphabétique',
      'Connaitre les correspondances entre les lettres et les sons',
      'Comprendre un texte et contrôler sa compréhension',
      'Pratiquer différentes formes de lecture',
      'Lire à haute voix',
  ] },
  { nom: 'ECRITURE', competences: [
      'Maitrisé les gestes de l’écriture cursive exécutés avec une vitesse et une sureté croissantes',
      'Adopter une stratégie de copie pour dépasser la copie lettre à lettre (Prise d’indice, mémorisation de mots ou groupe de mots)',
      'Lecture (Relire pour vérifier la conformité)',
      'Produire un travail propre et soigné',
      'Mise en œuvre d’une démarche de production de textes : des syllabes puis des phrases',
  ] },
  { nom: 'ETUDE DE LA LANGUE : GRAMMAIRE, ORTHOGRAPHE, LEXIQUE', competences: [
      'Trouver des synonymes, des antonymes, des mots de la même famille lexicale',
      'Identifier et trouver un ou des noms appartenant à une catégorie donnée',
      'Identifier une phrase',
      'Reconnaître les principaux constituants de la phrase : le sujet, le verbe (connaissance de propriétés permettant de l’identifier), les compléments (sans distinction)',
      'Différencier les principales classes de mots : le nom, le déterminant, l’adjectif, le verbe, le pronom personnel sujet, les mots invariables.',
      'Conjuguer oralement les verbes au présent, au futur, à l’imparfait et au passé composé.',
      'Passer de l’oral à l’écrit : connaître les correspondances graphologiques.',
      'Mémoriser l’orthographe du lexique le plus couramment employé',
      'Comprendre la notion de « chaîne d’accords » pour déterminant, nom, adjectif (singulier/pluriel ; masculin/féminin)',
      'Mémoriser l’orthographe des principaux mots invariables.',
      'Être capable de consulter un dictionnaire',
      'Activités Langagières – ANGLAIS',
      'Saluer, se présenter, demander à quelqu’un des nouvelles et réagir, donner de ses nouvelles.',
      'Formuler des souhaits basiques/ Utiliser des formules de politesse',
      'Répondre à des questions sur des sujets familiers',
      'Épeler des mots et des noms familiers',
      'Syntaxe de la conversation simple de type question/Réponse',
      'Reproduire un modèle oral',
      'Utiliser des expressions courtes ou phrases proches des modèles rencontrés lors des apprentissages pour se décrire.',
      'Lire à haute voix de manière expressive un texte bref',
      'Raconter une histoire courte à partir d’images ou de modèles déjà rencontrés.',
      'Répertoire élémentaire de mots sur les lieux d’habitation et les personnes de l’entourage de l’élève.',
  ] },
  { nom: 'MATHEMATIQUES', competences: [
      'Nombres et calcul',
      'Dénombrer, constituer et comparer des collections jusqu’à 30',
      'Comprendre et utiliser les des nombres entiers (jusqu’à 120) pour dénombrer, ordonner et comparer',
      'Nommer, lire, écrire, représenter des nombres entiers',
      'Résoudre des problèmes en utilisant des nombres entiers et le calcul',
      'Poser des additions en colonne avec ou sans retenues',
      'Grandeurs et mesures',
      'Comparer des objets selon plusieurs grandeurs et identifier qu’il s’agit d’une longueur, d’une masse, d’une contenance ou d’une durée',
      'Utiliser le lexique, les unités, les instruments de mesures spécifiques à ces grandeurs.',
      'Résoudre des problèmes, notamment de mesurage et de comparaison, en utilisant les opérations sur les grandeurs ou sur les nombres',
      'Lire, utiliser et tracer des graphiques et des diagrammes',
      'Géométrie',
      '(Se) repérer et (se) déplacer en utilisant des repères et des représentations',
      'Reconnaître, nommer, décrire, reproduire quelques solides (carré, cercle, triangle et rectangle)',
      'Reconnaitre, nommer, décrire, reproduire, construire quelques figures géométriques',
      'Reconnaître et utiliser les notions d’alignement, d’angle droit, d’égalité de longueurs, de milieu, de symétrie',
      'Partager des cercles et des rectangles en deux ou quatre parties égales, décrire ces parties en utilisant des mots moitié de, quart de',
  ] },
  { nom: 'SCIENCES', competences: [
      'Le vivant : le fonctionnement des organes dans le développement et le traitement de l’information',
      'L’espace et le système solaire : comprendre certains cycles et modèles',
      'Les propriétés du son et de la lumière',
      'Technologie',
  ] },
  { nom: 'QUESTIONNER LE MONDE', competences: [
      'Questionner le monde du vivant, de la matière et des objets',
      'A/ Qu’est-ce que la matière ?',
      'Comparer et mesurer la température, le volume, la masse de l’eau à l’état liquide et à l’état solide',
      'Reconnaître les états de l’eau et leur manifestation dans divers phénomènes naturels',
      'Mettre en œuvre des expériences simples impliquant l’eau et/ou l’air',
      'B/ Comment reconnaître le monde du vivant ?',
      'Identifier ce qui est un animal, végétal, minéral ou élaboré par des êtres vivants',
      'Identifier les interactions des êtres vivants entre eux et avec leur milieu',
      'Repérer les éléments permettant la réalisation d’un mouvement corporel (croissance, taille, masse, pointure, dentition.)',
      'Mettre en œuvre et apprécier quelques règles d’hygiène de vie : variété alimentaire, activité physique, habitude quotidienne de propreté…',
      'C/ Les objets techniques',
      'Comprendre la fonction et le fonctionnement des objets fabriqués',
      'Réaliser quelques objets et circuits électriques simples, en respectant des règles élémentaires de sécurité',
      'Commencer à s’approprier un environnement numérique',
      'Questionner l’espace et le temps',
      'A/ Se situer dans l’espace',
      'Se repérer dans l’espace et le représenter',
      'Situer un lieu sur une carte, sur un globe ou sur un écran numérique',
      'B/ Se situer dans le temps',
      'Se repérer dans le temps et mesurer des durées',
      'Repérer et situer quelques événements dans un long temps',
      'C/ Explorer les organisations du monde',
      'Comparer quelques modes de vie des hommes et des femmes, et quelques représentations du monde',
      'Comprendre qu’un espace et organisé',
      'Identifier des paysages',
  ] },
  { nom: 'ARTS PLASTIQUES ET EDUCATION MUSICALE', competences: [
      'Expérimenter, produire et créer',
      'Mettre en œuvre un projet artistique',
      'S’exprimer, analyser sa pratique, celle de ses pairs ; établir une relation avec celle des artistes, s’ouvrir à l’altérité',
      'Se repérer dans les domaines liés aux arts plastiques, être sensible aux questions de l’art',
      'Écouter, comparer des éléments sonores, des musiques',
      'Chanter une mélodie simple, une comptine ou un chant avec une intonation juste',
  ] },
  { nom: 'ENSEIGNEMENT MORAL ET CIVIQUE', competences: [
      'Se reconnaitre comme individu et élève',
      'Connaissance et maîtrise de soi',
      'Connaître et maîtriser les règles collectives de l’autonomie (être capable d’écoute, accepter la différence, mettre en œuvre les règles de communication dans un débat…)',
      'Connaître les règles d’hygiène et exigence d’intimité',
      'Prendre des responsabilités dans la classe et dans l’école',
  ] },
  { nom: 'EDUCATION PHYSIQUE', competences: [
      'Développe sa motricité et construire un langage du corps',
      'Produire une performance optimale, mesurable à une échéance donnée',
      'Adapter ses déplacements à des environnements variés',
      'S’exprimer devant les autres par une prestation artistique et/ou acrobatique',
      'Conduire et maîtriser un affrontement collectif ou interindividuel',
  ] }
  ],
  CE1: [
  { nom: 'LANGAGE', competences: [
      'Écouter pour comprendre des messages oraux ou des textes lus par un adulte',
      'Raconter et décrire seul un récit étudié en classe (Dire pour être entendu et compris)',
      'Participer à des échanges dans des situations diversifiées',
      'Échanger avec ses camarades, donner son avis (Adopter une distance critique par rapport au langage produit',
  ] },
  { nom: 'LECTURE ET COMPREHENSION DE L’ÉCRIT', competences: [
      'Identifier des mots, les mots-outils, les phrases rapidement (inconnus réguliers ou irréguliers mémorisés)',
      'Lire et comprendre des textes adaptés à la maturité et à la culture scolaire des élèves (comprendre et contrôler sa compréhension)',
      'Lire à haute voix avec fluidité, après préparation, un texte d’une demi-page ; participer à une lecture dialoguée après préparation',
      'Pratiquer différentes formes de lecture',
  ] },
  { nom: 'ECRITURE', competences: [
      'Copier ou transcrire, dans une écriture lisible un texte d’une dizaine de ligne en respectant la ponctuation, l’orthographe et en soignant la présentation.',
      'Rédiger un texte d’environ une demi-page, cohérent, organisé, ponctué et pertinent',
      'Lecture (Relire pour vérifier la conformité)',
      'Produire un travail propre et soigné',
      'Mise en œuvre d’une démarche de production de textes : des syllabes puis des phrases',
  ] },
  { nom: 'ETUDE DE LA LANGUE : GRAMMAIRE, ORTHOGRAPHE, LEXIQUE', competences: [
      'Trouver des synonymes, des antonymes, des mots de la même famille lexicale',
      'Identifier et trouver un ou des noms appartenant à une catégorie donnée',
      'Identifier une phrase',
      'Reconnaître les principaux constituants de la phrase : le sujet, le verbe (connaissance de propriétés permettant de l’identifier), les compléments (sans distinction)',
      'Différencier les principales classes de mots : le nom, le déterminant, l’adjectif, le verbe, le pronom personnel sujet, les mots invariables.',
      'Conjuguer oralement les verbes au présent, au futur, à l’imparfait et au passé composé.',
      'Passer de l’oral à l’écrit : connaître les correspondances graphologiques.',
      'Mémoriser l’orthographe du lexique le plus couramment employé',
      'Comprendre la notion de « chaîne d’accords » pour déterminant, nom, adjectif (singulier/pluriel ; masculin/féminin)',
      'Mémoriser l’orthographe des principaux mots invariables.',
      'Être capable de consulter un dictionnaire',
      'Activités Langagières – ANGLAIS',
      'Saluer, se présenter, demander à quelqu’un des nouvelles et réagir, donner de ses nouvelles.',
      'Formuler des souhaits basiques/ Utiliser des formules de politesse',
      'Répondre à des questions sur des sujets familiers',
      'Épeler des mots et des noms familiers',
      'Syntaxe de la conversation simple de type question/Réponse',
      'Reproduire un modèle oral',
      'Utiliser des expressions courtes ou phrases proches des modèles rencontrés lors des apprentissages pour se décrire.',
      'Lire à haute voix de manière expressive un texte bref',
      'Raconter une histoire courte à partir d’images ou de modèles déjà rencontrés.',
      'Répertoire élémentaire de mots sur les lieux d’habitation et les personnes de l’entourage de l’élève.',
  ] },
  { nom: 'MATHEMATIQUES', competences: [
      'Nombres et calcul',
      'Dénombrer, constituer et comparer des collections jusqu’à 30',
      'Comprendre et utiliser les des nombres entiers (jusqu’à 120) pour dénombrer, ordonner et comparer',
      'Nommer, lire, écrire, représenter des nombres entiers',
      'Résoudre des problèmes en utilisant des nombres entiers et le calcul',
      'Poser des additions en colonne avec ou sans retenues',
      'Grandeurs et mesures',
      'Comparer des objets selon plusieurs grandeurs et identifier qu’il s’agit d’une longueur, d’une masse, d’une contenance ou d’une durée',
      'Utiliser le lexique, les unités, les instruments de mesures spécifiques à ces grandeurs.',
      'Résoudre des problèmes, notamment de mesurage et de comparaison, en utilisant les opérations sur les grandeurs ou sur les nombres',
      'Lire, utiliser et tracer des graphiques et des diagrammes',
      'Géométrie',
      '(Se) repérer et (se) déplacer en utilisant des repères et des représentations',
      'Reconnaître, nommer, décrire, reproduire quelques solides (carré, cercle, triangle et rectangle)',
      'Reconnaitre, nommer, décrire, reproduire, construire quelques figures géométriques',
      'Reconnaître et utiliser les notions d’alignement, d’angle droit, d’égalité de longueurs, de milieu, de symétrie',
      'Partager des cercles et des rectangles en deux ou quatre parties égales, décrire ces parties en utilisant des mots moitié de, quart de',
  ] },
  { nom: 'SCIENCES', competences: [
      'Le vivant : le fonctionnement des organes dans le développement et le traitement de l’information',
      'L’espace et le système solaire : comprendre certains cycles et modèles',
      'Les propriétés du son et de la lumière',
      'Technologie',
  ] },
  { nom: 'QUESTIONNER LE MONDE', competences: [
      'Questionner le monde du vivant, de la matière et des objets',
      'A/ Qu’est-ce que la matière ?',
      'Comparer et mesurer la température, le volume, la masse de l’eau à l’état liquide et à l’état solide',
      'Reconnaître les états de l’eau et leur manifestation dans divers phénomènes naturels',
      'Mettre en œuvre des expériences simples impliquant l’eau et/ou l’air',
      'B/ Comment reconnaître le monde du vivant ?',
      'Identifier ce qui est un animal, végétal, minéral ou élaboré par des êtres vivants',
      'Identifier les interactions des êtres vivants entre eux et avec leur milieu',
      'Repérer les éléments permettant la réalisation d’un mouvement corporel (croissance, taille, masse, pointure, dentition.)',
      'Mettre en œuvre et apprécier quelques règles d’hygiène de vie : variété alimentaire, activité physique, habitude quotidienne de propreté…',
      'C/ Les objets techniques',
      'Comprendre la fonction et le fonctionnement des objets fabriqués',
      'Réaliser quelques objets et circuits électriques simples, en respectant des règles élémentaires de sécurité',
      'Commencer à s’approprier un environnement numérique',
      'Questionner l’espace et le temps',
      'A/ Se situer dans l’espace',
      'Se repérer dans l’espace et le représenter',
      'Situer un lieu sur une carte, sur un globe ou sur un écran numérique',
      'B/ Se situer dans le temps',
      'Se repérer dans le temps et mesurer des durées',
      'Repérer et situer quelques événements dans un long temps',
      'C/ Explorer les organisations du monde',
      'Comparer quelques modes de vie des hommes et des femmes, et quelques représentations du monde',
      'Comprendre qu’un espace et organisé',
      'Identifier des paysages',
  ] },
  { nom: 'ARTS PLASTIQUES ET EDUCATION MUSICALE', competences: [
      'Expérimenter, produire et créer',
      'Mettre en œuvre un projet artistique',
      'S’exprimer, analyser sa pratique, celle de ses pairs ; établir une relation avec celle des artistes, s’ouvrir à l’altérité',
      'Se repérer dans les domaines liés aux arts plastiques, être sensible aux questions de l’art',
      'Écouter, comparer des éléments sonores, des musiques',
      'Chanter une mélodie simple, une comptine ou un chant avec une intonation juste',
  ] },
  { nom: 'ENSEIGNEMENT MORAL ET CIVIQUE', competences: [
      'Se reconnaitre comme individu et élève',
      'Connaissance et maîtrise de soi',
      'Connaître et maîtriser les règles collectives de l’autonomie (être capable d’écoute, accepter la différence, mettre en œuvre les règles de communication dans un débat…)',
      'Connaître les règles d’hygiène et exigence d’intimité',
      'Prendre des responsabilités dans la classe et dans l’école',
  ] },
  { nom: 'EDUCATION PHYSIQUE', competences: [
      'Développe sa motricité et construire un langage du corps',
      'Produire une performance optimale, mesurable à une échéance donnée',
      'Adapter ses déplacements à des environnements variés',
      'S’exprimer devant les autres par une prestation artistique et/ou acrobatique',
      'Conduire et maîtriser un affrontement collectif ou interindividuel',
  ] }
  ],
  CE2: [
  { nom: 'LANGAGE ORAL', competences: [
      'Écouter pour comprendre des messages oraux ou des textes lus par un adulte',
      'Raconter et décrire seul un récit étudié en classe (Dire pour être entendu et compris)',
      'Participer à des échanges dans des situations diversifiées',
      'Échanger avec ses camarades, donner son avis (Adopter une distance critique par rapport au langage produit',
  ] },
  { nom: 'VOCABULAIRE', competences: [
      'Enrichir son vocabulaire dans tous les enseignements (s’appuie sur la morphologie des mots pour en trouver le sens, consulte avec aisance un dictionnaire)',
      'Établir des relations entre les mots',
      'Mémoriser l’orthographe lexicales (écrire correctement sous la dictée les mots réguliers et irréguliers fréquents)',
  ] },
  { nom: 'LECTURE ET COMPREHENSION DE L’ÉCRIT', competences: [
      'Identifier des mots, les mots-outils, les phrases de manière de plus en plus aisée (inconnus réguliers ou irréguliers mémorisés)',
      'Connaitre le nom des lettres et l’ordre alphabétique',
      'Connaitre les correspondances entre les lettres et les sons',
      'Comprendre un texte et contrôler sa compréhension',
      'Pratiquer différentes formes de lecture',
      'Lire à haute voix',
      'Devenir lecteur (Lire de manière autonome 5 à 10 œuvres complètes et variées)',
  ] },
  { nom: 'ECRITURE', competences: [
      'Écrire et transcrire avec fluidité toutes les minuscules et majuscules en cursive',
      'Encoder puis écrire sous dictée (Orthographier correctement les mots fréquents, réguliers et irréguliers et des phrases dans le cadre de dictées)',
      'Copier et acquérir des stratégies de copie (en conjuguant vitesse et exactitude et en respectant les mises en pages)',
      'Réviser et améliorer l’écrit que l’on a produit',
  ] },
  { nom: 'ETUDE DE LA LANGUE : GRAMMAIRE, ORTHOGRAPHE, LEXIQUE', competences: [
      'Se repérer dans la phrase simple (savoir trouver des synonymes, des antonymes, des mots de la même famille)',
      'Maîtriser les relations entre l’oral et l’écrit',
      'Différencier et nommer les principales classes de mots (déterminant, nom commun, nom propre, adjectif, verbe, pronom personnel, sujet et adverbes',
      'Utiliser la ponctuation de fin de phrase (. ! ?) et reconnaître les trois types de phrase : déclarative, interrogative, exclamative',
      'Reconnaître les deux éléments constitutifs de la phrase simple le groupe sujet (GS) et le groupe verbal (GV), le complément d’objet direct (COD), le complément d’objet indirect (COI) et l’attribut du sujet',
      'Identifier le radical et la terminaison',
      'Donner l’infinitif du verbe conjugué',
      'Mémoriser au présent, futur simple, imparfait, et passé composé : être et avoir, les verbes du 1er groupe, certains verbes du 3ème groupe (faire, aller, dire, venir, pouvoir, voir, vouloir, prendre)',
  ] },
  { nom: 'LANGUE VIVANTE – ANGLAIS', competences: [
      'Saluer, se présenter, demander à quelqu’un des nouvelles et réagir, donner de ses nouvelles.',
      'Suivre le fil d’une histoire simple (comptines, chansons, albums)',
      'Répondre à des questions sur des sujets familiers',
      'Épeler des mots et des noms familiers',
      'Syntaxe de la conversation simple de type question/Réponse',
      'Reproduire un modèle oral',
      'Utiliser des expressions courtes ou phrases proches des modèles rencontrés lors des apprentissages pour se décrire.',
      'Lire à haute voix de manière expressive un texte bref',
      'Raconter une histoire courte à partir d’images ou de modèles déjà rencontrés.',
      'Répertoire élémentaire de mots sur les lieux d’habitation et les personnes de l’entourage de l’élève.',
  ] },
  { nom: 'MATHEMATIQUES', competences: [
      'Nombres, calcul et résolution de problèmes',
      'Comprendre et utiliser des nombres entiers pour dénombre, ordonner, repérer, comparer (nombres inférieurs à 10000)',
      'Nommer, lire, écrire, représenter des nombres entiers.',
      'Calculer avec des nombres entiers',
      'Résoudre des problèmes en utilisant des nombres entiers et le calcul',
      'Grandeurs et mesures',
      'Résoudre des problèmes comportant la mesure et l’estimation de durées de volumes de masses',
      'Représenter et interpréter des données (connaissances et interprétations des unités et symboles associés m, dm, cm, mm, km ou g, kg, t)',
      'Comparer, estimer, mesurer des longueurs, des masses, des contenances, des durées',
      'Utiliser le lexique, les unités, les instruments de mesures spécifiques à ces grandeurs',
      'Comparer, estimer, mesurer des grandeurs géométriques avec des nombres : longueurs (périmètre), air, volume, angle',
      'Espace et géométrie',
      'Comprendre que les polygones de différentes catégories peuvent avoir des caractéristiques communes qui forment un ensemble de figures plus larges',
      'Quadrilatères : reconnaître les losanges, les rectangles et les carrées',
      'Tracer des quadrilatères autres que les quadrilatères particuliers',
      'Partager des figures en partie égales et exprimer ces parties avec des fractions',
      'Organisation et gestion des données',
      'Présenter, lire et interpréter des données dans un tableau à double entrée ou un diagramme en barres',
      'Résoudre des problèmes en utilisant les données d’un tableau à double entrée ou d’un diagramme en barre',
  ] },
  { nom: 'QUESTIONNER LE MONDE (SCIENCES)', competences: [
      'Le vivant, sa diversité et ses fonctions',
      'Reconnaître les différents types d’êtres vivants (animaux, végétaux)',
      'Comprendre les besoins vitaux (air, eau, alimentation)',
      'Découvrir la chaîne alimentaire et les relations entre les êtres vivants',
      'Identifier les stades de développement (naissance, croissance, reproduction)',
      'Comprendre les bons gestes pour la santé (alimentation équilibrée, hygiène, sommeil, sport)',
      '2 Les objets techniques',
      'Identifier la fonction d’un objet et les matériaux qui le composent',
      'Comprendre comment un objet répond à un besoin',
      'Découvrir les leviers, roues, engrenages, circuits simples (notions de force, mouvement, électricité basique)',
      'Concevoir ou modifier un petit objet technique (maquette, circuit, mécanisme simple)',
      '3 La matière, l’énergie et les changements d’état',
      'Observer et décrire la matière (solide, liquide, gazeux)',
      'Comprendre les changements d’état (fonte, solidification, évaporation, condensation)',
      'Découvrir quelques formes d’énergie (lumière, chaleur, électricité)',
      'Apprendre des gestes écologiques : économie d’énergie, recyclage, tri',
      '4 Se repérer dans l’espace et le temps (Histoire/Géographie)',
      'Se repérer dans l’espace et le représenter',
      'Situer un lieu sur une carte, ou sur un écran',
      'Se repérer dans le temps et mesurer des durées',
      'Repérer et situer quelques événements dans un temps long',
      'Comprendre comment des événements, des personnes et des courants de pensées ont influé l’histoire des communautés locales et régionales',
      'Utiliser l’esprit critique pour comprendre le contexte historique des événements, des populations et des lieux',
      'Comparer quelques modes de vies des hommes et des femmes, et quelques représentations du monde',
  ] },
  { nom: 'ARTS PLASTIQUES ET EDUCATION MUSICALE', competences: [
      'Expérimenter, produire et créer des productions plastiques de natures diverses',
      'Mettre en œuvre un projet artistique individuel ou collectif',
      'S’exprimer, analyser sa pratique, celle de ses pairs ; établir une relation avec celle des artistes, s’ouvrir à l’altérité',
      'Se repérer dans les domaines liés aux arts plastiques, être sensible aux questions de l’art',
      'Écouter, comparer des éléments sonores, des musiques',
      'Chanter une mélodie simple, une comptine ou un chant avec une intonation juste',
  ] },
  { nom: 'ENSEIGNEMENT MORAL ET CIVIQUE', competences: [
      'Connaître et maîtriser les règles collectives de l’autonomie (être capable d’écoute, accepter la différence, mettre en œuvre les règles de communication dans un débat…)',
      'Connaître les règles d’hygiène et exigence d’intimité',
      'Connaître et respecter les règles de la classe et de l’école',
      'Prendre des responsabilités dans la classe et dans l’école',
      'Être sensible à la notion de bien commun',
      'Connaître la république et son fonctionnement',
  ] },
  { nom: 'EDUCATION PHYSIQUE', competences: [
      'Produire une performance optimale, mesurable à une échéance donnée',
      'Adapter ses déplacements à des environnements variés',
      'S’exprimer devant les autres par une prestation artistique et/ou acrobatique',
      'Conduire et maîtriser un affrontement collectif ou interindividuel',
  ] }
  ],
};

export const ELEM_NOTES: Record<string, TemplateDomaine[]> = {
  CP: [
  { nom: 'Français', competences: [
      'Langage oral',
      'Lecture/compréhension de l’écrit',
      'Écriture',
      'Grammaire/ Orthographe',
  ] },
  { nom: 'Mathématiques', competences: [
      'Nombres / Calculs',
      'Grandeurs/ Mesures',
      'Géométrie',
      'Résolution de problèmes',
  ] },
  { nom: 'Éducation à la Science et à la vie sociale', competences: [
      'Questionner le monde',
      'Questionner l’espace et le temps',
      'Initiation Scientifique et Technologique',
  ] },
  { nom: 'Éducation artistique/ Musicale', competences: [
      'Dessin, chant, expression créative',
  ] },
  { nom: 'Éducation physique (EPS)', competences: [
      'Coordination, jeux collectifs',
  ] },
  { nom: 'Enseignement Moral et civique', competences: [
      'Soi et les autres/ Le droit et la règle/L’engagement',
  ] },
  { nom: 'Anglais', competences: [
      'English Language',
      'Mathématics',
      'Science',
      'Hand writing',
  ] },
  { nom: 'Intélligence Artificielle / Informatique', competences: [
      'Découverte et Compréhension/Observation et Logique/ Esprit critique et usage responsable',
  ] },
  { nom: 'Vie scolaire', competences: [
      'Respect, autonomie, écoute, participation',
  ] }
  ],
  CE1: [
  { nom: 'Français', competences: [
      'Langage oral',
      'Lecture/compréhension de l’écrit',
      'Écriture',
      'Grammaire/ Orthographe',
  ] },
  { nom: 'Mathématiques', competences: [
      'Nombres / Calculs',
      'Grandeurs/ Mesures',
      'Géométrie',
  ] },
  { nom: 'Éducation à la Science et à la vie sociale', competences: [
      'Questionner le monde',
      'Questionner l’espace et le temps',
  ] },
  { nom: 'Éducation artistique/ Musicale', competences: [
      'Dessin, chant, expression créative',
  ] },
  { nom: 'Éducation physique (EPS)', competences: [
      'Coordination, jeux collectifs',
  ] },
  { nom: 'Enseignement Moral et civique', competences: [
      'Le soi et les autres/ Le droit et la règle/L’engagement',
  ] },
  { nom: 'Anglais', competences: [
      'English Language',
      'Mathématics',
      'Science',
      'Hand writing',
  ] },
  { nom: 'Intélligence Artificielle / Informatique', competences: [
      'Découverte et Compréhension/Observation et Logique/ Esprit critique et usage responsable',
  ] },
  { nom: 'Vie scolaire', competences: [
      'Respect, autonomie, écoute, participation',
  ] }
  ],
  CE2: [
  { nom: 'Français', competences: [
      'Langage oral',
      'Lecture/compréhension de l’écrit',
      'Écriture',
      'Grammaire/ Orthographe',
  ] },
  { nom: 'Mathématiques', competences: [
      'Nombres / Calculs/ Résolution de problèmes',
      'Grandeurs/ Mesures',
      'Espace et Géométrie',
      'Organisation et gestion de données',
  ] },
  { nom: 'Éducation à la Science et à la vie sociale', competences: [
      'Questionner le monde',
      'Questionner l’espace et le temps',
  ] },
  { nom: 'Éducation artistique/ Musicale', competences: [
      'Dessin, chant, expression créative',
  ] },
  { nom: 'Éducation physique (EPS)', competences: [
      'Coordination, jeux collectifs',
  ] },
  { nom: 'Enseignement Moral et civique', competences: [
      'Soi et les autres/ Le droit et la règle/L’engagement',
  ] },
  { nom: 'Anglais', competences: [
      'English Language',
      'Mathématics',
      'Science',
      'Hand writing',
  ] },
  { nom: 'Intélligence Artificielle / Informatique', competences: [
      'Découverte et Compréhension/Observation et Logique/ Esprit critique et usage responsable',
  ] },
  { nom: 'Vie scolaire', competences: [
      'Respect, autonomie, écoute, participation',
  ] }
  ],
};
